export const ImgData = {
  "Beauty": "../src/assets/Beauty.png",
  "Fragrances": "../src/assets/Fragrances.png",
  "Furniture": "../src/assets/Furniture.png",
  "Groceries": "../src/assets/Groceries.png",
  "Home Decoration": "../src/assets/HomeDecoration.png",
  "Kitchen Accessories": "../src/assets/KitchenAccessories.png",
  "Laptops": "../src/assets/Laptops.png",
  "Mens Shirts": "../src/assets/MensShirts.png",
  "Mens Shoes": "../src/assets/MensShoes.png",
  "Mens Watches": "../src/assets/MensWatches.png",
  "Mobile Accessories": "../src/assets/MobileAccessories.png",
  "Motorcycle": "../src/assets/Motorcycle.png",
  "Skin Care": "../src/assets/SkinCare.png",
  "Smartphones": "../src/assets/Smartphones.png",
  "Sports Accessories": "../src/assets/SportsAccessories.png",
  "Sunglasses": "../src/assets/Sunglasses.png",
  "Tablets": "../src/assets/Tablets.png",
  "Tops": "../src/assets/Tops.png",
  "Vehicle": "../src/assets/Vehicle.png",
  "Womens Bags": "../src/assets/WomensBags.png",
  "Womens Dresses": "../src/assets/WomensDresses.png",
  "Womens Jewellery": "../src/assets/WomensJewellery.png",
  "Womens Shoes": "../src/assets/WomensShoes.png",
  "Womens Watches": "../src/assets/WomensWatches.png"
};
